apiVersion: v1
kind: Service
metadata:
  name: anjouexplore-app
  namespace: anjouexplore
  labels:
    app: anjouexplore
    component: app
spec:
  type: ClusterIP
  selector:
    app: anjouexplore
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
