apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: anjouexplore
  namespace: anjouexplore
  labels:
    app: anjouexplore
  annotations:
    # Métadonnées
    app.kubernetes.io/name: anjouexplore
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/description: "Site web Anjou Explore - Escapades nature, patrimoine et gastronomie"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`anjouexplore.ratons.ovh`)
      kind: Rule
      # Pas de middleware Authelia : l'application gère son propre 2FA (JWT + Google Authenticator)
      services:
        - name: anjouexplore-app
          port: 80
  tls:
    secretName: ratons-ovh-wildcard-tls
